[general]
import = ["themes/themes/sonokai.toml"]

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
size = 12.0

normal = { family = "Monaco Nerd Font Mono", style = "Regular" }
# bold = { family = "Monaco Nerd Font Mono", style = "Bold" }
# bold_italic = { family = "Monaco Nerd Font Mono", style = "Bold Italic" }
# italic = { family = "Monaco Nerd Font Mono", style = "Italic" }

[mouse]
bindings = []

[keyboard]
bindings = [
  { key = "N", mods = "Control", mode = "Search", action = "SearchFocusNext" },
  { key = "P", mods = "Control", mode = "Search", action = "SearchFocusPrevious" },
  { key = "ArrowDown", mode = "Search", action = "SearchFocusNext" },
  { key = "ArrowUp", mode = "Search", action = "SearchFocusPrevious" },
]
