#!/bin/bash

# set -x

INIT=$(realpath "$0")
DOTS=$(dirname "$INIT")
DEPS=$DOTS/deps
OS="$(uname -s)"

source $DEPS/util.sh

# deps
case "$OS" in
Linux)
	if [ -f "/etc/arch-release" ] || [ -f "/etc/artix-release" ]; then
		$DEPS/pacman.sh $DEPS
	elif [ -f "/etc/fedora-release" ] || [ -f "/etc/redhat-release" ]; then
		$DEPS/dnf.sh $DEPS
	elif [ -f "/etc/gentoo-release" ]; then
		$DEPS/emerge.sh $DEPS
	else
		# assume apt
		$DEPS/apt.sh $DEPS
	fi
	;;
FreeBSD)
	$DEPS/pkg.sh $DEPS
	;;
NetBSD)
	$DEPS/pkgin.sh $DEPS
	;;
OpenBSD)
	$DEPS/pkg_add.sh $DEPS
	;;
Darwin)
	$DEPS/brew.sh $DEPS
	;;
*)
	message "$OS is not supported, exit..."
	exit 1
	;;
esac

# git config
git config --global user.email "linrongbin16@outlook.com"
git config --global user.name "linrongbin16"
git config --global core.fsmonitor true
git config --global core.untrackedcache true

# rust
install_or_skip "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y" "cargo"
source "$HOME/.cargo/env"
install_or_skip "cargo install fd-find" "fd"
install_or_skip "cargo install ripgrep" "rg"
install_or_skip "cargo install --locked bat" "bat"
install_or_skip "cargo install exa" "exa"

# go
# see: https://github.com/kerolloz/go-installer
if [ -d go-installer ]; then
	rm -rf go-installer
fi
install_or_skip "git clone --depth=1 https://github.com/kerolloz/go-installer.git && ./go-installer/go.sh" "go"
install_or_skip "go install github.com/jesseduffield/lazygit@latest" "lazygit"

# prompt
if [ ! -d ~/.mzpt ]; then
	git clone https://github.com/linrongbin16/mzpt.git ~/.mzpt
fi
echo '' >>~/.zshrc
echo '# mzpt prompt theme' >>~/.zshrc
echo '[ -f ~/.mzpt/mzpt.zsh ] && source ~/.mzpt/mzpt.zsh' >>~/.zshrc

# alias
echo '' >>~/.zshrc
echo '# ls' >>~/.zshrc
echo 'alias l="exa -lh"' >>~/.zshrc
echo 'alias ll="exa -alh"' >>~/.zshrc

echo '' >>~/.zshrc
echo '# lazygit' >>~/.zshrc
echo 'alias lg="lazygit"' >>~/.zshrc

echo '' >>~/.zshrc
echo '# git alias' >>~/.zshrc
echo 'alias gs="git status"' >>~/.zshrc
echo 'alias gp="git pull"' >>~/.zshrc
echo 'alias gP="git push"' >>~/.zshrc
echo 'alias ga="git add"' >>~/.zshrc
echo 'alias gc="git commit"' >>~/.zshrc
echo 'alias gck="git checkout"' >>~/.zshrc
echo 'alias gb="git branch"' >>~/.zshrc
echo 'alias gm="git merge"' >>~/.zshrc
