[window]
startup_mode = "Maximized"
dynamic_title = true

[scrolling]
history = 100000

[mouse]
hide_when_typing = true
bindings = []

[keyboard]
bindings = [
  { key = "N", mods = "Control", mode = "Search", action = "SearchFocusNext" },
  { key = "P", mods = "Control", mode = "Search", action = "SearchFocusPrevious" },
  { key = "ArrowDown", mode = "Search", action = "SearchFocusNext" },
  { key = "ArrowUp", mode = "Search", action = "SearchFocusPrevious" },
]

[general]
# Create 'alacritty-custom.toml' file, and include themes:
#
# ```
# [general]
# import = ["alacritty-theme/themes/everforest_dark.toml"]
# [font]
# size = 13.0
# normal = { family = "MonoLisa Nerd Font", style = "Regular" }
# bold = { family = "MonoLisa Nerd Font", style = "Bold" }
# bold_italic = { family = "MonoLisa Nerd Font", style = "Bold Italic" }
# italic = { family = "MonoLisa Nerd Font", style = "Italic" }
# ```
import = ["alacritty-custom.toml"]
